kumuluzee:
  name: photo-management-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/PhotoDS
    connection-url: jdbc:postgresql://192.168.99.100:5433/photo #TODO check this
    username: dbuser
    password: postgres
    max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: photo-endpoint
      url-pattern: /v1/photos/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/PhotoDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="user-service">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
app-properties:
  external-services:
    enabled: true